---
- include: "{{ project_deploy_hook_pre_share | default('../hooks/example.yml') }}"

- name: Check if project folders exist
  stat:
    path: "{{ deploy_helper.current_path }}/{{ item }}"
  register: project_folder_paths
  with_items: project_copy_folders

- name: Copy project folders
  command: cp -rp {{ deploy_helper.current_path }}/{{ item.item }} {{ deploy_helper.new_release_path }}
  with_items: project_folder_paths.results
  when: item.stat.exists == True

- name: Ensure shared sources are present
  file:
    path: "{{ deploy_helper.shared_path }}/{{ item.src }}"
    state: "{{ item.type | default('directory') }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items: project_shared_children

- name: Ensure shared paths are absent
  file:
    path: "{{ deploy_helper.new_release_path }}/{{ item.path }}"
    state: absent
  with_items: project_shared_children

- name: Create shared symlinks
  file:
    path: "{{ deploy_helper.new_release_path }}/{{ item.path }}"
    src: "{{ deploy_helper.shared_path }}/{{ item.src }}"
    state: link
  with_items: project_shared_children

- include: "{{ project_deploy_hook_post_share | default('../hooks/example.yml') }}"
